IMPORTING REQUIRED MODULES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
from scipy import stats
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor

IMPORTING OUR DATASET

In [2]:
df=pd.read_csv(r'/content/Agrofood_emission.csv')

INSPECTING THE DATASET

In [3]:
df.head()

,Area,Year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,...,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature °C
0,Afghanistan,1990,14.7237,0.0557,205.6077,686.00,0.0,11.807483,63.1152,-2388.803,...,319.1763,0.0,0.0,NaN,9655167.0,2593947.0,5348387.0,5346409.0,2198.963539,0.536167
1,Afghanistan,1991,14.7237,0.0557,209.4971,678.16,0.0,11.712073,61.2125,-2388.803,...,342.3079,0.0,0.0,NaN,10230490.0,2763167.0,5372959.0,5372208.0,2323.876629,0.020667
2,Afghanistan,1992,14.7237,0.0557,196.5341,686.00,0.0,11.712073,53.3170,-2388.803,...,349.1224,0.0,0.0,NaN,10995568.0,2985663.0,6028494.0,6028939.0,2356.304229,-0.259583
3,Afghanistan,1993,14.7237,0.0557,230.8175,686.00,0.0,11.712073,54.3617,-2388.803,...,352.2947,0.0,0.0,NaN,11858090.0,3237009.0,7003641.0,7000119.0,2368.470529,0.101917
4,Afghanistan,1994,14.7237,0.0557,242.0494,705.60,0.0,11.712073,53.9874,-2388.803,...,367.6784,0.0,0.0,NaN,12690115.0,3482604.0,7733458.0,7722096.0,2500.768729,0.372250

In [4]:
#Display all columns
pd.set_option('display.max_columns', None)
df

,Area,Year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,Net Forest conversion,Food Household Consumption,Food Retail,On-farm Electricity Use,Food Packaging,Agrifood Systems Waste Disposal,Food Processing,Fertilizers Manufacturing,IPPU,Manure applied to Soils,Manure left on Pasture,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature °C
0,Afghanistan,1990,14.7237,0.0557,205.6077,686.0000,0.0,11.807483,63.1152,-2388.8030,0.0000,79.0851,109.6446,14.2666,67.631366,691.7888,252.21419,11.997000,209.9778,260.1431,1590.5319,319.1763,0.0,0.0,NaN,9655167.0,2593947.0,5348387.0,5346409.0,2198.963539,0.536167
1,Afghanistan,1991,14.7237,0.0557,209.4971,678.1600,0.0,11.712073,61.2125,-2388.8030,0.0000,80.4885,116.6789,11.4182,67.631366,710.8212,252.21419,12.853900,217.0388,268.6292,1657.2364,342.3079,0.0,0.0,NaN,10230490.0,2763167.0,5372959.0,5372208.0,2323.876629,0.020667
2,Afghanistan,1992,14.7237,0.0557,196.5341,686.0000,0.0,11.712073,53.3170,-2388.8030,0.0000,80.7692,126.1721,9.2752,67.631366,743.6751,252.21419,13.492900,222.1156,264.7898,1653.5068,349.1224,0.0,0.0,NaN,10995568.0,2985663.0,6028494.0,6028939.0,2356.304229,-0.259583
3,Afghanistan,1993,14.7237,0.0557,230.8175,686.0000,0.0,11.712073,54.3617,-2388.8030,0.0000,85.0678,81.4607,9.0635,67.631366,791.9246,252.21419,14.055900,201.2057,261.7221,1642.9623,352.2947,0.0,0.0,NaN,11858090.0,3237009.0,7003641.0,7000119.0,2368.470529,0.101917
4,Afghanistan,1994,14.7237,0.0557,242.0494,705.6000,0.0,11.712073,53.9874,-2388.8030,0.0000,88.8058,90.4008,8.3962,67.631366,831.9181,252.21419,15.126900,182.2905,267.6219,1689.3593,367.6784,0.0,0.0,NaN,12690115.0,3482604.0,7733458.0,7722096.0,2500.768729,0.372250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6960,Zimbabwe,2016,1190.0089,232.5068,70.9451,7.4088,0.0,75.000000,251.1465,76500.2982,10662.4408,251.2681,443.0872,428.4352,22.910800,1077.2392,317.07440,2585.080847,858.9820,96.1332,2721.1459,282.5994,0.0,0.0,417.3150,10934468.0,5215894.0,6796658.0,7656047.0,98491.026347,1.120250
6961,Zimbabwe,2017,1431.1407,131.1324,108.6262,7.9458,0.0,67.000000,255.7975,76500.2982,10662.4408,203.1236,445.3881,304.7852,18.985700,1093.3441,332.77590,1227.240253,889.4250,81.2314,2744.8763,255.5900,0.0,0.0,398.1644,11201138.0,5328766.0,6940631.0,7810471.0,97159.311553,0.046500
6962,Zimbabwe,2018,1557.5830,221.6222,109.9835,8.1399,0.0,66.000000,327.0897,76500.2982,10662.4408,211.1539,492.8599,346.8512,19.057000,1108.5523,348.51070,1127.687805,966.2650,81.0712,2790.0949,257.2735,0.0,0.0,465.7735,11465748.0,5447513.0,7086002.0,7966181.0,97668.308205,0.516333
6963,Zimbabwe,2019,1591.6049,171.0262,45.4574,7.8322,0.0,73.000000,290.1893,76500.2982,10662.4408,228.6381,542.5922,350.2168,17.951400,1121.3255,327.82090,2485.528399,945.9420,85.7211,2828.7215,267.5224,0.0,0.0,444.2335,11725970.0,5571525.0,7231989.0,8122618.0,98988.062799,0.985667
6964,Zimbabwe,2020,481.9027,48.4197,108.3022,7.9733,0.0,73.000000,238.7639,76500.2982,10662.4408,213.9211,568.0445,350.2168,16.675400,1134.1634,307.41450,1227.240253,940.4200,85.3143,2829.7457,266.7316,0.0,0.0,444.2335,11980005.0,5700460.0,7385220.0,8284447.0,96505.221853,0.189000

In [5]:
#Let's understand our data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6965 entries, 0 to 6964
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Area                             6965 non-null   object
 1   Year                             6965 non-null   int64
 2   Savanna fires                    6934 non-null   float64
 3   Forest fires                     6872 non-null   float64
 4   Crop Residues                    5576 non-null   float64
 5   Rice Cultivation                 6965 non-null   float64
 6   Drained organic soils (CO2)      6965 non-null   float64
 7   Pesticides Manufacturing         6965 non-null   float64
 8   Food Transport                   6965 non-null   float64
 9   Forestland                       6472 non-null   float64
 10  Net Forest conversion            6472 non-null   float64
 11  Food Household Consumption       6492 non-null   float64
 12  Food Retail                      6965 non-null   float64
 13  On-farm Electricity Use          6965 non-null   float64
 14  Food Packaging                   6965 non-null   float64
 15  Agrifood Systems Waste Disposal  6965 non-null   float64
 16  Food Processing                  6965 non-null   float64
 17  Fertilizers Manufacturing        6965 non-null   float64
 18  IPPU                             6222 non-null   float64
 19  Manure applied to Soils          6037 non-null   float64
 20  Manure left on Pasture           6965 non-null   float64
 21  Manure Management                6037 non-null   float64
 22  Fires in organic soils           6965 non-null   float64
 23  Fires in humid tropical forests  6810 non-null   float64
 24  On-farm energy use               6009 non-null   float64
 25  Rural population                 6965 non-null   float64
 26  Urban population                 6965 non-null   float64
 27  Total Population - Male          6965 non-null   float64
 28  Total Population - Female        6965 non-null   float64
 29  total_emission                   6965 non-null   float64
 30  Average Temperature °C           6965 non-null   float64
dtypes: float64(29), int64(1), object(1)
memory usage: 1.6+ MB

In [6]:
df.describe()

,Year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,Net Forest conversion,Food Household Consumption,Food Retail,On-farm Electricity Use,Food Packaging,Agrifood Systems Waste Disposal,Food Processing,Fertilizers Manufacturing,IPPU,Manure applied to Soils,Manure left on Pasture,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature °C
count,6965.000000,6934.000000,6872.000000,5576.000000,6965.000000,6965.000000,6965.000000,6965.000000,6472.000000,6.472000e+03,6492.000000,6965.000000,6965.000000,6965.000000,6965.000000,6965.000000,6965.000000,6.222000e+03,6037.000000,6965.000000,6037.000000,6965.000000,6810.000000,6009.000000,6.965000e+03,6.965000e+03,6.965000e+03,6.965000e+03,6.965000e+03,6965.000000
mean,2005.124910,1188.390893,919.302167,998.706309,4259.666673,3503.228636,333.418393,1939.581760,-17828.285678,1.760564e+04,4847.580384,2043.210539,1626.681460,1658.629808,6018.444633,3872.724461,3035.723356,1.999150e+04,923.225603,3518.026573,2263.344946,1210.315532,668.452931,3008.982252,1.785774e+07,1.693230e+07,1.761963e+07,1.732447e+07,6.409124e+04,0.872989
std,8.894665,5246.287783,3720.078752,3700.345330,17613.825187,15861.445678,1429.159367,5616.748808,81832.210543,1.011575e+05,25789.143619,8494.249260,9343.182193,11481.343725,22156.742542,19838.216846,11693.029064,1.114209e+05,3226.992039,9103.556202,7980.542461,22669.847760,3264.879486,12637.864430,8.901521e+07,6.574362e+07,7.603993e+07,7.251711e+07,2.283130e+05,0.555930
min,1990.000000,0.000000,0.000000,0.000200,0.000000,0.000000,0.000000,0.000100,-797183.079000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.340000,0.000100,0.001900,0.000000e+00,0.049000,0.000700,0.432900,0.000000,0.000000,0.031900,0.000000e+00,0.000000e+00,2.500000e+02,2.700000e+02,-3.918841e+05,-1.415833
25%,1997.000000,0.000000,0.000000,11.006525,181.260800,0.000000,6.000000,27.958600,-2848.350000,0.000000e+00,11.399950,26.818500,8.037600,67.631366,86.680500,209.587728,360.358799,3.903153e+01,16.303000,139.669900,37.632100,0.000000,0.000000,13.291900,9.731100e+04,2.173860e+05,2.013260e+05,2.078900e+05,5.221244e+03,0.511333
50%,2005.000000,1.651850,0.517900,103.698200,534.817400,0.000000,13.000000,204.962800,-62.920000,4.444000e+01,155.471100,172.042600,29.120700,74.018133,901.275700,344.760200,1115.052400,8.037066e+02,120.443900,972.567400,269.856300,0.000000,0.000000,141.096300,1.595322e+06,2.357581e+06,2.469660e+06,2.444135e+06,1.214765e+04,0.834300
75%,2013.000000,111.081400,64.950775,377.640975,1536.640000,690.408800,116.325487,1207.000900,0.000000,4.701746e+03,1377.151950,1075.999100,499.944700,281.791000,3006.442100,1236.913400,2024.869900,6.155175e+03,460.120200,2430.792600,1126.818900,0.000000,9.577875,1136.925400,8.177340e+06,8.277123e+06,9.075924e+06,9.112588e+06,3.513973e+04,1.206750
max,2020.000000,114616.401100,52227.630600,33490.074100,164915.255600,241025.069600,16459.000000,67945.765000,171121.076000,1.605106e+06,466288.200700,133784.065300,165676.299000,175741.306100,213289.701600,274253.512500,170826.423300,1.861641e+06,34677.360300,92630.756800,70592.646500,991717.543100,51771.256800,248879.176900,9.000991e+08,9.020778e+08,7.435866e+08,7.133419e+08,3.115114e+06,3.558083

In [7]:
df.describe(include='object')

               Area
count          6965
unique          236
top     Afghanistan
freq             31

# **HANDLING NULL VALUES**

In [8]:
#Displaying only columns with null(missing) values with percentage
null_columns=df.columns[df.isnull().any()]
null_summary=df[null_columns].isnull().sum()
null_percentage = ((null_summary / len(df)) * 100).round(2)
null_dataframe=pd.DataFrame({'Column':null_columns,'Null Count':null_summary,'Percentage %':null_percentage}).sort_values(by='Percentage %',ascending=False)
display(null_dataframe)

,Column,Null Count,Percentage %
Crop Residues,Crop Residues,1389,19.94
On-farm energy use,On-farm energy use,956,13.73
Manure applied to Soils,Manure applied to Soils,928,13.32
Manure Management,Manure Management,928,13.32
IPPU,IPPU,743,10.67
Forestland,Forestland,493,7.08
Net Forest conversion,Net Forest conversion,493,7.08
Food Household Consumption,Food Household Consumption,473,6.79
Fires in humid tropical forests,Fires in humid tropical forests,155,2.23
Forest fires,Forest fires,93,1.34
Savanna fires,Savanna fires,31,0.45

IT SEEMS THERE IS A PATTERN IN NULL VALUES BETWEEN
*    MANURE APPLIED TO SOILS AND MANURE MANAGEMENT
*    FORESTLAND AND NET FOREST CONVERSION

In [9]:
# Check correlation between the columns with potential patterns
correlation = df[['Manure applied to Soils', 'Manure Management']].corr()

# Display the correlation matrix
print(correlation)

                         Manure applied to Soils  Manure Management
Manure applied to Soils                 1.000000           0.975795
Manure Management                       0.975795           1.000000

In [10]:
# Check correlation between the columns with potential patterns
correlation = df[['Forestland', 'Net Forest conversion']].corr()

# Display the correlation matrix
print(correlation)

                       Forestland  Net Forest conversion
Forestland               1.000000              -0.359537
Net Forest conversion   -0.359537               1.000000

THE ABOVE CORRELATION TEST SUGGESTS THAT THOSE TWO COLUMNS ARE CLOSELY RELATED AND MISSING VALUES ARE LIKELY ASSOCIATED WITH EACH OTHER.

FILLING THE NULL VALUES WITH 0

In [11]:
for columns in null_columns:
  df.fillna({columns:0},inplace=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6965 entries, 0 to 6964
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Area                             6965 non-null   object
 1   Year                             6965 non-null   int64
 2   Savanna fires                    6965 non-null   float64
 3   Forest fires                     6965 non-null   float64
 4   Crop Residues                    6965 non-null   float64
 5   Rice Cultivation                 6965 non-null   float64
 6   Drained organic soils (CO2)      6965 non-null   float64
 7   Pesticides Manufacturing         6965 non-null   float64
 8   Food Transport                   6965 non-null   float64
 9   Forestland                       6965 non-null   float64
 10  Net Forest conversion            6965 non-null   float64
 11  Food Household Consumption       6965 non-null   float64
 12  Food Retail                      6965 non-null   float64
 13  On-farm Electricity Use          6965 non-null   float64
 14  Food Packaging                   6965 non-null   float64
 15  Agrifood Systems Waste Disposal  6965 non-null   float64
 16  Food Processing                  6965 non-null   float64
 17  Fertilizers Manufacturing        6965 non-null   float64
 18  IPPU                             6965 non-null   float64
 19  Manure applied to Soils          6965 non-null   float64
 20  Manure left on Pasture           6965 non-null   float64
 21  Manure Management                6965 non-null   float64
 22  Fires in organic soils           6965 non-null   float64
 23  Fires in humid tropical forests  6965 non-null   float64
 24  On-farm energy use               6965 non-null   float64
 25  Rural population                 6965 non-null   float64
 26  Urban population                 6965 non-null   float64
 27  Total Population - Male          6965 non-null   float64
 28  Total Population - Female        6965 non-null   float64
 29  total_emission                   6965 non-null   float64
 30  Average Temperature °C           6965 non-null   float64
dtypes: float64(29), int64(1), object(1)
memory usage: 1.6+ MB

In [13]:
df

,Area,Year,Savanna fires,Forest fires,Crop Residues,Rice Cultivation,Drained organic soils (CO2),Pesticides Manufacturing,Food Transport,Forestland,Net Forest conversion,Food Household Consumption,Food Retail,On-farm Electricity Use,Food Packaging,Agrifood Systems Waste Disposal,Food Processing,Fertilizers Manufacturing,IPPU,Manure applied to Soils,Manure left on Pasture,Manure Management,Fires in organic soils,Fires in humid tropical forests,On-farm energy use,Rural population,Urban population,Total Population - Male,Total Population - Female,total_emission,Average Temperature °C
0,Afghanistan,1990,14.7237,0.0557,205.6077,686.0000,0.0,11.807483,63.1152,-2388.8030,0.0000,79.0851,109.6446,14.2666,67.631366,691.7888,252.21419,11.997000,209.9778,260.1431,1590.5319,319.1763,0.0,0.0,0.0000,9655167.0,2593947.0,5348387.0,5346409.0,2198.963539,0.536167
1,Afghanistan,1991,14.7237,0.0557,209.4971,678.1600,0.0,11.712073,61.2125,-2388.8030,0.0000,80.4885,116.6789,11.4182,67.631366,710.8212,252.21419,12.853900,217.0388,268.6292,1657.2364,342.3079,0.0,0.0,0.0000,10230490.0,2763167.0,5372959.0,5372208.0,2323.876629,0.020667
2,Afghanistan,1992,14.7237,0.0557,196.5341,686.0000,0.0,11.712073,53.3170,-2388.8030,0.0000,80.7692,126.1721,9.2752,67.631366,743.6751,252.21419,13.492900,222.1156,264.7898,1653.5068,349.1224,0.0,0.0,0.0000,10995568.0,2985663.0,6028494.0,6028939.0,2356.304229,-0.259583
3,Afghanistan,1993,14.7237,0.0557,230.8175,686.0000,0.0,11.712073,54.3617,-2388.8030,0.0000,85.0678,81.4607,9.0635,67.631366,791.9246,252.21419,14.055900,201.2057,261.7221,1642.9623,352.2947,0.0,0.0,0.0000,11858090.0,3237009.0,7003641.0,7000119.0,2368.470529,0.101917
4,Afghanistan,1994,14.7237,0.0557,242.0494,705.6000,0.0,11.712073,53.9874,-2388.8030,0.0000,88.8058,90.4008,8.3962,67.631366,831.9181,252.21419,15.126900,182.2905,267.6219,1689.3593,367.6784,0.0,0.0,0.0000,12690115.0,3482604.0,7733458.0,7722096.0,2500.768729,0.372250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6960,Zimbabwe,2016,1190.0089,232.5068,70.9451,7.4088,0.0,75.000000,251.1465,76500.2982,10662.4408,251.2681,443.0872,428.4352,22.910800,1077.2392,317.07440,2585.080847,858.9820,96.1332,2721.1459,282.5994,0.0,0.0,417.3150,10934468.0,5215894.0,6796658.0,7656047.0,98491.026347,1.120250
6961,Zimbabwe,2017,1431.1407,131.1324,108.6262,7.9458,0.0,67.000000,255.7975,76500.2982,10662.4408,203.1236,445.3881,304.7852,18.985700,1093.3441,332.77590,1227.240253,889.4250,81.2314,2744.8763,255.5900,0.0,0.0,398.1644,11201138.0,5328766.0,6940631.0,7810471.0,97159.311553,0.046500
6962,Zimbabwe,2018,1557.5830,221.6222,109.9835,8.1399,0.0,66.000000,327.0897,76500.2982,10662.4408,211.1539,492.8599,346.8512,19.057000,1108.5523,348.51070,1127.687805,966.2650,81.0712,2790.0949,257.2735,0.0,0.0,465.7735,11465748.0,5447513.0,7086002.0,7966181.0,97668.308205,0.516333
6963,Zimbabwe,2019,1591.6049,171.0262,45.4574,7.8322,0.0,73.000000,290.1893,76500.2982,10662.4408,228.6381,542.5922,350.2168,17.951400,1121.3255,327.82090,2485.528399,945.9420,85.7211,2828.7215,267.5224,0.0,0.0,444.2335,11725970.0,5571525.0,7231989.0,8122618.0,98988.062799,0.985667
6964,Zimbabwe,2020,481.9027,48.4197,108.3022,7.9733,0.0,73.000000,238.7639,76500.2982,10662.4408,213.9211,568.0445,350.2168,16.675400,1134.1634,307.41450,1227.240253,940.4200,85.3143,2829.7457,266.7316,0.0,0.0,444.2335,11980005.0,5700460.0,7385220.0,8284447.0,96505.221853,0.189000

# **RENAMING COLUMNS**

In [14]:
df.columns

Index(['Area', 'Year', 'Savanna fires', 'Forest fires', 'Crop Residues',
       'Rice Cultivation', 'Drained organic soils (CO2)',
       'Pesticides Manufacturing', 'Food Transport', 'Forestland',
       'Net Forest conversion', 'Food Household Consumption', 'Food Retail',
       'On-farm Electricity Use', 'Food Packaging',
       'Agrifood Systems Waste Disposal', 'Food Processing',
       'Fertilizers Manufacturing', 'IPPU', 'Manure applied to Soils',
       'Manure left on Pasture', 'Manure Management', 'Fires in organic soils',
       'Fires in humid tropical forests', 'On-farm energy use',
       'Rural population', 'Urban population', 'Total Population - Male',
       'Total Population - Female', 'total_emission',
       'Average Temperature °C'],
      dtype='object')

In [15]:
for column in df.columns:
  column_name=column.lower().replace('-','')
  df.rename(columns={column:column_name},inplace=True)
df.columns

Index(['area', 'year', 'savanna fires', 'forest fires', 'crop residues',
       'rice cultivation', 'drained organic soils (co2)',
       'pesticides manufacturing', 'food transport', 'forestland',
       'net forest conversion', 'food household consumption', 'food retail',
       'onfarm electricity use', 'food packaging',
       'agrifood systems waste disposal', 'food processing',
       'fertilizers manufacturing', 'ippu', 'manure applied to soils',
       'manure left on pasture', 'manure management', 'fires in organic soils',
       'fires in humid tropical forests', 'onfarm energy use',
       'rural population', 'urban population', 'total population  male',
       'total population  female', 'total_emission', 'average temperature °c'],
      dtype='object')

In [16]:
for column in df.columns:
  column_name=column.lower().replace('  ',' ')
  df.rename(columns={column:column_name},inplace=True)

In [17]:
for column in df.columns:
  column_name=column.lower().replace(' ','_')
  df.rename(columns={column:column_name},inplace=True)

In [18]:
strip=['_°c','(co2)']
for s in strip:
  df.columns=[col.replace(s,'') for col in df.columns]
df.columns

Index(['area', 'year', 'savanna_fires', 'forest_fires', 'crop_residues',
       'rice_cultivation', 'drained_organic_soils_',
       'pesticides_manufacturing', 'food_transport', 'forestland',
       'net_forest_conversion', 'food_household_consumption', 'food_retail',
       'onfarm_electricity_use', 'food_packaging',
       'agrifood_systems_waste_disposal', 'food_processing',
       'fertilizers_manufacturing', 'ippu', 'manure_applied_to_soils',
       'manure_left_on_pasture', 'manure_management', 'fires_in_organic_soils',
       'fires_in_humid_tropical_forests', 'onfarm_energy_use',
       'rural_population', 'urban_population', 'total_population_male',
       'total_population_female', 'total_emission', 'average_temperature'],
      dtype='object')

# **DUPLICATES**

In [19]:
duplicates = df[df.duplicated()]
duplicates

Empty DataFrame
Columns: [area, year, savanna_fires, forest_fires, crop_residues, rice_cultivation, drained_organic_soils_, pesticides_manufacturing, food_transport, forestland, net_forest_conversion, food_household_consumption, food_retail, onfarm_electricity_use, food_packaging, agrifood_systems_waste_disposal, food_processing, fertilizers_manufacturing, ippu, manure_applied_to_soils, manure_left_on_pasture, manure_management, fires_in_organic_soils, fires_in_humid_tropical_forests, onfarm_energy_use, rural_population, urban_population, total_population_male, total_population_female, total_emission, average_temperature]
Index: []

In [20]:
df['area'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belgium-Luxembourg', 'Belize', 'Benin', 'Bermuda',
       'Bhutan', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Cayman Islands', 'Central African Republic', 'Chad',
       'Channel Islands', 'Chile', 'China', 'China, Hong Kong SAR',
       'China, Macao SAR', 'China, mainland', 'China, Taiwan Province of',
       'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica',
       'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Czechoslovakia',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Ethiopia PDR',
       'Falkland Islands (Malvinas)', 'Faroe Islands', 'Fiji', 'Finland',
       'France', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia',
       'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guadeloupe', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Holy See', 'Honduras', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Iran (Islamic Republic of)', 'Iraq',
       'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait',
       'Kyrgyzstan', "Lao People's Democratic Republic", 'Latvia',
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein',
       'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia',
       'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique',
       'Mauritania', 'Mauritius', 'Mayotte', 'Mexico',
       'Micronesia (Federated States of)', 'Monaco', 'Mongolia',
       'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands (Kingdom of the)',
       'Netherlands Antilles (former)', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North Macedonia',
       'Northern Mariana Islands', 'Norway', 'Oman',
       'Pacific Islands Trust Territory', 'Pakistan', 'Palau',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Republic of Korea', 'Republic of Moldova', 'Romania',
       'Russian Federation', 'Rwanda',
       'Saint Helena, Ascension and Tristan da Cunha',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Serbia and Montenegro', 'Seychelles',
       'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Sudan (former)', 'Suriname',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan',
       'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'United States Virgin Islands', 'Uruguay', 'USSR', 'Uzbekistan',
       'Vanuatu', 'Venezuela (Bolivarian Republic of)', 'Viet Nam',
       'Wallis and Futuna Islands', 'Western Sahara', 'Yemen',
       'Yugoslav SFR', 'Zambia', 'Zimbabwe'], dtype=object)

We can see some of the country names are repeated. Some of them are because the data collected when the countries were not split.
This includes:
*   Czechoslovakia split into Czechia and Slovakia in 1993.
*   Ethiopia was called Ethiopia PDR till 1992.
*   Sudan split into Sudan and South Sudan in 2011.
*   The Union of Soviet Socialist Republics (USSR) dissolved in 1991    
    and formed 15 independent states.
*   Yugoslavia (Yugoslav SFR) dissolved in the early 1990s, giving rise to:
Serbia, Montenegro, Croatia, Bosnia and Herzegovina, Slovenia, North Macedonia, and Kosovo.
*   Netherlands Antilles dissolved in 2010 into several entities, including:
Curaçao, Sint Maarten, and others that remain part of the Kingdom of the Netherlands.
*   The union of Serbia and Montenegro dissolved into two independent countries in 2006.

Let's consider the data after 2011(Occurence of Last boundary split). Because,
*   Older data might not reflect current trends, especially for countries that have undergone significant changes (e.g., splits, economic reforms).
*   Post-2011 data may align better with modern boundaries and reporting standards.
*   Many countries standardized their data reporting formats after 2010 due to international agreements like the Kyoto Protocol,Paaris agreement and subsequent updates.

In [34]:
df_updated=df[df['year']>2011]

In [36]:
df_updated['area'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'British Virgin Islands',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Cayman Islands',
       'Central African Republic', 'Chad', 'Channel Islands', 'Chile',
       'China', 'China, Hong Kong SAR', 'China, Macao SAR',
       'China, mainland', 'China, Taiwan Province of', 'Colombia',
       'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czechia',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Falkland Islands (Malvinas)',
       'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Polynesia',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar',
       'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Isle of Man',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius',
       'Mayotte', 'Mexico', 'Micronesia (Federated States of)', 'Monaco',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands (Kingdom of the)', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North Macedonia',
       'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Republic of Korea', 'Republic of Moldova', 'Romania',
       'Russian Federation', 'Rwanda',
       'Saint Helena, Ascension and Tristan da Cunha',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic',
       'Tajikistan', 'Thailand', 'Timor-Leste', 'Togo', 'Tokelau',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam',
       'Wallis and Futuna Islands', 'Western Sahara', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [39]:
df_updated.loc[:, 'area'] = df_updated['area'].replace({
    'Congo': 'Republic of Congo',
    'Venezuela (Bolivarian Republic of)': 'Venezuela',
    'Viet Nam': 'Vietnam',
    'Iran (Islamic Republic of)': 'Iran',
    'Bolivia (Plurinational State of)': 'Bolivia',
    'Micronesia (Federated States of)': 'Micronesia',
    'Netherlands (Kingdom of the)': 'Netherlands',
    "Democratic People's Republic of Korea": 'North Korea',
    'Republic of Korea': 'South Korea',
    'Falkland Islands (Malvinas)': 'Malvinas'
})

Now let's Group Countries:

French Polynesia: Should be categorized under France (as it is an overseas territory).

Falkland Islands (Malvinas): This is a British overseas territory, and categorized under United Kingdom.

Pacific Islands Trust Territory: This refers to a former trust territory, and categorized under United States.

China, Hong Kong SAR
China, Macao SAR
China, mainland
China, Taiwan Province of : Categorised under China

In [41]:
df_updated.loc[:,'area'] = df_updated['area'].replace({
    'China, Hong Kong SAR': 'China',
    'China, Macao SAR': 'China',
    'China, mainland': 'China',
    'China, Taiwan Province of': 'China',
    'French Polynesia': 'France',
    'Falkland Islands (Malvinas)': 'United Kingdom of Great Britain and Northern Ireland',
    'Pacific Islands Trust Territory': 'United States of America '
})

In [46]:
df_updated=df_updated.reset_index(drop=True)

# **OUTLIER**

HERE I HAVE DECIDED TO KEEP THE OUTLIERS AS IT MIGHT HAVE **RARE BUT VALID CASES**

# **FINAL DATAFRAME AFTER PRE-PROCESSING**

In [47]:
df_updated

,area,year,savanna_fires,forest_fires,crop_residues,rice_cultivation,drained_organic_soils_,pesticides_manufacturing,food_transport,forestland,net_forest_conversion,food_household_consumption,food_retail,onfarm_electricity_use,food_packaging,agrifood_systems_waste_disposal,food_processing,fertilizers_manufacturing,ippu,manure_applied_to_soils,manure_left_on_pasture,manure_management,fires_in_organic_soils,fires_in_humid_tropical_forests,onfarm_energy_use,rural_population,urban_population,total_population_male,total_population_female,total_emission,average_temperature
0,Afghanistan,2012,2.8955,0.0000,445.5958,803.6000,0.0,107.386444,530.8213,-246.2191,0.0000,534.4065,271.2397,47.1675,339.83367,2743.2372,1326.917597,29.443300,266.4513,441.8546,2798.7363,836.9089,0.0,0.0,0.0000,23280663.0,7416295.0,15399105.0,15067373.0,11280.276511,0.344167
1,Afghanistan,2013,3.1595,0.0000,455.0727,803.6000,0.0,76.061874,391.0777,-246.2191,0.0000,833.2319,276.2396,66.6996,353.93064,2870.4764,1441.160481,29.981400,333.5334,432.0026,2741.0994,832.8961,0.0,0.0,0.0000,23997856.0,7733832.0,15946572.0,15594637.0,11694.004195,1.290917
2,Afghanistan,2014,2.6796,0.0000,473.4174,862.4000,0.0,49.782873,304.1804,-246.2191,0.0000,1094.1338,333.4255,78.6716,353.93064,2976.2524,1484.197070,28.639400,282.6155,437.6203,2770.4672,842.5037,0.0,0.0,0.0000,24703798.0,8054222.0,16543889.0,16172321.0,12128.698284,0.468667
3,Afghanistan,2015,0.8454,0.0000,403.3181,642.8800,0.0,81.852555,440.0315,-246.2191,0.0000,1570.3394,370.6039,75.1614,353.93064,3090.5068,1645.129815,27.235400,256.7030,423.5038,2719.1528,797.9007,0.0,0.0,0.0000,25368923.0,8367571.0,17071446.0,16682054.0,12652.876111,1.103917
4,Afghanistan,2016,1.6558,0.0000,387.6130,466.4800,0.0,54.909681,340.8931,154.6574,0.0000,1649.8382,425.9346,84.2970,353.93064,3201.0961,1627.654458,27.846900,302.7560,421.9268,2692.9570,793.9377,0.0,0.0,0.0000,25985093.0,8670939.0,17520861.0,17115346.0,12988.384380,1.839417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2038,Zimbabwe,2016,1190.0089,232.5068,70.9451,7.4088,0.0,75.000000,251.1465,76500.2982,10662.4408,251.2681,443.0872,428.4352,22.91080,1077.2392,317.074400,2585.080847,858.9820,96.1332,2721.1459,282.5994,0.0,0.0,417.3150,10934468.0,5215894.0,6796658.0,7656047.0,98491.026347,1.120250
2039,Zimbabwe,2017,1431.1407,131.1324,108.6262,7.9458,0.0,67.000000,255.7975,76500.2982,10662.4408,203.1236,445.3881,304.7852,18.98570,1093.3441,332.775900,1227.240253,889.4250,81.2314,2744.8763,255.5900,0.0,0.0,398.1644,11201138.0,5328766.0,6940631.0,7810471.0,97159.311553,0.046500
2040,Zimbabwe,2018,1557.5830,221.6222,109.9835,8.1399,0.0,66.000000,327.0897,76500.2982,10662.4408,211.1539,492.8599,346.8512,19.05700,1108.5523,348.510700,1127.687805,966.2650,81.0712,2790.0949,257.2735,0.0,0.0,465.7735,11465748.0,5447513.0,7086002.0,7966181.0,97668.308205,0.516333
2041,Zimbabwe,2019,1591.6049,171.0262,45.4574,7.8322,0.0,73.000000,290.1893,76500.2982,10662.4408,228.6381,542.5922,350.2168,17.95140,1121.3255,327.820900,2485.528399,945.9420,85.7211,2828.7215,267.5224,0.0,0.0,444.2335,11725970.0,5571525.0,7231989.0,8122618.0,98988.062799,0.985667
2042,Zimbabwe,2020,481.9027,48.4197,108.3022,7.9733,0.0,73.000000,238.7639,76500.2982,10662.4408,213.9211,568.0445,350.2168,16.67540,1134.1634,307.414500,1227.240253,940.4200,85.3143,2829.7457,266.7316,0.0,0.0,444.2335,11980005.0,5700460.0,7385220.0,8284447.0,96505.221853,0.189000

In [48]:
df_updated.describe()

,year,savanna_fires,forest_fires,crop_residues,rice_cultivation,drained_organic_soils_,pesticides_manufacturing,food_transport,forestland,net_forest_conversion,food_household_consumption,food_retail,onfarm_electricity_use,food_packaging,agrifood_systems_waste_disposal,food_processing,fertilizers_manufacturing,ippu,manure_applied_to_soils,manure_left_on_pasture,manure_management,fires_in_organic_soils,fires_in_humid_tropical_forests,onfarm_energy_use,rural_population,urban_population,total_population_male,total_population_female,total_emission,average_temperature
count,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2.043000e+03,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2043.000000,2.043000e+03,2.043000e+03,2.043000e+03,2.043000e+03,2.043000e+03,2043.000000
mean,2016.000000,1066.603355,865.224798,938.641677,4331.252447,3619.959716,364.833781,2389.071522,-17021.143286,13557.170337,6362.261512,3195.474928,1982.585650,2126.737598,6420.036413,4388.715551,3604.269607,2.685620e+04,832.439022,3813.589375,1999.817500,1165.722854,635.709104,2630.855397,1.754491e+07,2.119405e+07,1.970277e+07,1.935578e+07,7.612603e+04,1.248834
std,2.582621,4766.535064,3755.486835,3882.894613,17691.043685,17171.139031,1416.873420,6628.874801,86957.871748,66298.875677,36681.174149,12554.724627,12149.101089,15647.735558,23727.134281,23099.836257,14552.580785,1.564890e+05,3079.297250,9658.277542,7437.653047,21247.747174,3243.773037,12602.631387,8.258697e+07,8.455309e+07,8.303017e+07,7.911849e+07,2.879297e+05,0.507286
min,2012.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.196700,-731109.224700,0.000000,0.000000,0.000400,0.011600,0.000200,0.369900,0.014800,0.009300,0.000000e+00,0.000000,0.000700,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,2.500000e+02,2.700000e+02,-2.524824e+05,-0.403167
25%,2014.000000,0.000000,0.000000,0.033500,246.407276,0.000000,10.000000,49.000150,-1939.198800,0.000000,10.512700,44.644000,12.027150,67.549033,105.201100,209.587728,376.493607,1.233335e+01,4.593650,119.601800,14.081200,0.000000,0.000000,7.349850,1.147205e+05,3.200980e+05,2.762065e+05,2.462235e+05,5.496038e+03,0.908708
50%,2016.000000,1.592900,0.129500,50.078700,578.415600,0.000000,20.000000,336.505800,-5.025300,4.847000,189.865800,329.398500,36.256800,77.393651,986.752200,389.710576,1215.065700,8.807176e+02,87.770200,1083.382700,200.228000,0.000000,0.000000,75.342900,1.681437e+06,3.105679e+06,2.853236e+06,2.794260e+06,1.378060e+04,1.205400
75%,2018.000000,106.941450,36.567750,323.300350,1539.088450,677.203100,138.799256,1463.285100,0.000000,3824.631800,1318.934900,1557.869600,522.648700,341.071184,3221.828350,1583.305850,2293.565448,7.840921e+03,409.313000,2679.683600,944.792400,0.000000,2.710250,781.067950,9.348544e+06,9.903787e+06,1.066250e+07,1.104480e+07,4.085352e+04,1.545958
max,2020.000000,112381.013500,33523.882400,33490.074100,152668.113400,241025.069600,12154.000000,67945.765000,76500.298200,780902.697700,466288.200700,133784.065300,165676.299000,175741.306100,213289.701600,274253.512500,170826.423300,1.861641e+06,29016.982500,92630.756800,67022.150300,569991.244000,33302.486100,139388.923600,9.000991e+08,9.020778e+08,7.435866e+08,7.133419e+08,3.115114e+06,3.558083

In [49]:
df_updated.to_csv(r'CO2_PrePro.csv', index=False)

In [50]:
import os
print(os.getcwd())

/content